Repository xitu/tensorflow, pull requests merged in 2018-02, with the labels that each got.

#151 translate: add filesys plugin
  tensorflow/docs_src/extend/add_filesys.md
Labels: 校对认领, 正在校对

#145 Embedding
  tensorflow/docs_src/programmers_guide/embedding.md
Labels: 正在校对

#155 Translation/broadcasting.md
  tensorflow/docs_src/performance/xla/broadcasting.md
Labels: 正在校对

#160 finish translate tfcompile
  tensorflow/docs_src/performance/xla/tfcompile.md
Labels: 校对认领

#159 编写数据读写器
  tensorflow/docs_src/extend/new_data_formats.md
Labels: 校对认领

#152 在其他语言中绑定 TensorFlow
  tensorflow/docs_src/extend/language_bindings.md
Labels: 正在校对

#148 Distributed
  tensorflow/docs_src/deploy/distributed.md
Labels: 正在校对

#156 Translation/developing new backend.md
  tensorflow/docs_src/performance/xla/broadcasting.md
  tensorflow/docs_src/performance/xla/developing_new_backend.md
Labels: 正在校对

#154 Translation/add a new op.md
  tensorflow/docs_src/extend/adding_an_op.md
Labels: 翻译完成

#150 如何在 Hadoop 上运行 Tensorflow
  tensorflow/docs_src/deploy/hadoop.md
Labels: 正在校对
